DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

March_Stones/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomeView, HistoryView, ContactView, MapView


app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('history/', HistoryView.as_view(), name="history"),
    path('map/', MapView.as_view(), name="map"),
    path('contact/', ContactView.as_view(), name="contact"),
    ]

core/views.py
from django.shortcuts import render
from django.conf import settings
from django.views.generic import TemplateView, View


class HomeView(TemplateView):
    template_name = 'index.html'


class HistoryView(TemplateView):
    template_name = 'history.html'


class ContactView(TemplateView):
    template_name = 'contact.html'


class MapView(View):
    def get(self, request):
        context = {'api_key': settings.GOOGLE_MAP_API_KEY,}
        return render(request, 'map.html', context)

templates/base.html
{% load static %}

<html lang="en">
<head>
    <title>March Stones</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|Playfair+Display:,300, 400, 700"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block map %}

    {% endblock map%}

</head>
<body>

{% block content %}


{% endblock content %}


<!-- loader -->
<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#f4b214"/>
    </svg>
</div>

{% include 'script.html' %}

{% block map_script %}
{% endblock map_script %}

</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}

<div class="site-wrap">

    <a href="#" class="border px-3 py-2 bg-secondary offcanvas-toggle js-offcanvas-toggle">Menu</a>
    <div class="offcanvas_menu" id="offcanvas_menu">
        <ul class="mb-5">
            <li><a href="{% url 'core:home' %}">Home</a></li>
            <li><a href="{% url 'core:history' %}">Short History</a></li>
            <li><a href="{% url 'core:map' %}">Map</a></li>
            <li class="active"><a href="{% url 'core:contact' %}">Contact</a></li>
        </ul>
        <ul class="social">
            <li><a target="_blank" href="https://www.facebook.com/mateusz.wrobel.796" class="mr-2 mb-2"><i
                    class="fa fa-facebook"></i></a></li>
            <li><a target="_blank" href="https://github.com/mateuszwwwrobel" class="mr-2 mb-2"><i
                    class="fa fa-github"></i></a></li>
            <li><a target="_blank" href="https://www.youtube.com/channel/UCqbh_cQEJo81E6RvjHllU5w/videos"
                   class="mr-2 mb-2"><i class="fa fa-youtube"></i></a></li>
        </ul>

        </br><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
        All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
            href="https://colorlib.com" target="_blank">Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

    </div>

    <aside style="background-image: url(/static/img/profile.jpg);"></aside>
    <main>
        <h1 class="mb-5">Contact</h1>
        <h4>Please feel free to contact if you have any question.</h4>
        <hr>
        <h5>Send an email to a following address:</h5>
        <h6><a href="mailto:mateusz.wwwrobel@gmail.com">mateusz.wwwrobel@gmail.com</a></h6>
        <hr>
    </main>
</div>

{% endblock content %}

templates/history.html
{% extends 'base.html' %}

{% block content %}


<div class="site-wrap">

    <a href="#" class="border px-3 py-2 bg-secondary offcanvas-toggle js-offcanvas-toggle">Menu</a>
    <div class="offcanvas_menu" id="offcanvas_menu">
        <ul class="mb-5">
            <li><a href="{% url 'core:home' %}">Home</a></li>
            <li class="active"><a href="{% url 'core:history' %}">Short History</a></li>
            <li><a href="{% url 'core:map' %}">Map</a></li>
            <li><a href="{% url 'core:contact' %}">Contact</a></li>
        </ul>
        <ul class="social">
            <li><a target="_blank" href="https://www.facebook.com/mateusz.wrobel.796" class="mr-2 mb-2"><i
                    class="fa fa-facebook"></i></a></li>
            <li><a target="_blank" href="https://github.com/mateuszwwwrobel" class="mr-2 mb-2"><i
                    class="fa fa-github"></i></a></li>
            <li><a target="_blank" href="https://www.youtube.com/channel/UCqbh_cQEJo81E6RvjHllU5w/videos"
                   class="mr-2 mb-2"><i class="fa fa-youtube"></i></a></li>
        </ul>

        </br><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
        All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
            href="https://colorlib.com" target="_blank">Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

    </div>

    <aside style="background-image: url(/static/img/profile.jpg);"></aside>
    <main>

        <h1 class="mb-5">Short History</h1>
        <p class="text-dark">This is the story of how Aberdeen acquired its boundaries and ultimately
            established itself as the city we know today. Walking or riding this
            boundary by following stone markers was an important tradition in
            Aberdeen. This leaflet explores the history of the Freedom Lands and
            provides details on how to continue the tradition of ‘Riding the
            Marches’.</p>

        <h2>The Freedom Lands</h2>
        <div class='text-dark'>
            <p>In 1319, when the Kingdom of Scotland was passing through a period of depression and the victorious King
                Robert the Bruce felt he had an honourable duty to
                perform to those who helped him establish the independence of the Kingdom, a regular feudal Charter of
                the burgh of Aberdeen and of the Stocket forest was granted
                the burgesses. The Forest of the Stocket, together with certain additional areas, comprises what is
                known as "The Freedom Lands".</p>

            <h2>The March Stones</h2>
            <p>There are two sets of boundary stones: the inner and the outer. The
                inner march stones mark the boundary of the crofts that ringed the
                medieval Royal Burgh of Aberdeen. The outer march stones define a
                much larger area known as the Freedom Lands. These lands went on to
                become the right and responsibility of the medieval and later Royal
                Burgh of Aberdeen. The name ‘march stones’ derives from the 16th
                century meaning of march as a boundary.</p>

            <h2>Boundary Markers</h2>
            <p>The earliest boundary markers were probably natural features such as
                burns and stones (described as ‘earthfast’ stones), with the addition of
                small purpose-built cairns. The first description of the marches dates
                back to a ‘riding of the marches’ in 1525. The practice of riding the
                boundary lines was intended to ensure they were being observed and
                respected, and that no adjacent landowners had encroached onto the
                town’s lands. These rides were accompanied by a great deal of
                ceremony and feasting.</p>
            <p>From the description of 1525 it is certain that there had been no
                standardised marking system. However, large ‘earthfast’ stones are a
                common feature in the records of this riding: some were described as
                including saucers, others as having a varied number of holes. It is
                possible that the saucer marks were filled with lead and then the
                town’s mark (or possibly seal) was impressed into it. Although, from a
                description of March Stone 1 made in 1578, it would seem that the
                town’s mark had been engraved into this particular stone. Moreover,
                through the 16th and 17th centuries there are repeated references to
                cairns next to march stones. In a riding of the marches in 1673, several
                cairns were ordered to be erected to mark the line of the marches on
                the Chapman road (this track ran from Aberdeen, out through Newhills
                to the Chapman ford, from stones No 44-34). This may have been an
                older practice, in spite of which, none of these ‘march cairns’ survive.</p>
            <p>It was after 1790 that the saucer stone system was replaced by a new
                system of lettered and numbered stones. This style, which is still with
                us today, has a number coupled with the letters ABD for Aberdeen and
                in the case of the inner march stones the additional letters CR for
                either City Royalty or City Regality. In the years immediately following
                1790 the stones up to number 48 were replaced with the new letter
                stones and the entire series was completed by 1810. The new series
                was not entirely the same as the older one had been; some stones
                were omitted whilst a number of new stones were
                introduced. Over the years the courses of older natural
                boundaries (such as burns) had been altered, thus
                necessitating some changes in the series.</p>
        </div>


        <p class="mt-5">Reference List:</p>
        <p>1. <a class="text-secondary" href="https://aberdeenmarchstones.co.uk/">The Burgesses of Guild of the Royal
            Burgh and City of Aberdeen</a></p>
        <p>2. <a class="text-secondary" href="https://www.visitabdn.com/assets/March-Stones-ILV-Final-Draft.pdf">Visit
            ABDN</a></p>
    </main>
</div>

{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}


<div class="site-wrap">
    <a href="#" class="border px-3 py-2 bg-secondary offcanvas-toggle js-offcanvas-toggle">Menu</a>
    <div class="offcanvas_menu" id="offcanvas_menu">
        <ul class="mb-5">
            <li class="active"><a href="{% url 'core:home' %}">Home</a></li>
            <li><a href="{% url 'core:history' %}">Short History</a></li>
            <li><a href="{% url 'core:map' %}">Map</a></li>
            <li><a href="{% url 'core:contact' %}">Contact</a></li>
        </ul>

        <ul class="social">
            <li><a target="_blank" href="https://www.facebook.com/mateusz.wrobel.796" class="mr-2 mb-2"><i
                    class="fa fa-facebook"></i></a></li>
            <li><a target="_blank" href="https://github.com/mateuszwwwrobel" class="mr-2 mb-2"><i
                    class="fa fa-github"></i></a></li>
            <li><a target="_blank" href="https://www.youtube.com/channel/UCqbh_cQEJo81E6RvjHllU5w/videos"
                   class="mr-2 mb-2"><i class="fa fa-youtube"></i></a></li>
        </ul>

        <div>
            </br><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </div>
    </div>

    <aside style="background-image: url(static/img/profile.jpg); transform: rotate(360deg);"></aside>

    <main>
        <h1 class="mb-0">March Stones of The Freedom Lands of Aberdeen</h1>
        <div class="mb-5">
            <p class="text-dark lead mb-3">This website will introduce you to an unknown history of march stones.
            Discover a mystery written between the narrow streets of the city and its surroundings.</p>

            <p class="text-dark">Please refer to <a href="{% url 'core:history' %}">History</a> to read more about them.
            </p>
            <p class="text-dark">Please find a <a href="{% url 'core:map' %}">Map</a> with locations of all of them.
                Please be aware that some of them are not publicly accessible.</p>
            <p class="text-dark">Let's travel back in time!</p>


        </div>


        <p>
            <a target="_blank" href="https://www.facebook.com/mateusz.wrobel.796" class="pr-2 mb-2">Facebook<i
                    class="pl-2 fa fa-facebook"></i></a>
            <a target="_blank" href="https://github.com/mateuszwwwrobel" class="pr-2 mb-2">Github<i
                    class="pl-2 fa fa-github"></i></a>
            <a target="_blank" href="https://www.youtube.com/channel/UCqbh_cQEJo81E6RvjHllU5w/videos" class="pr-2 mb-2">Youtube<i
                    class="pl-2 fa fa-youtube"></i></a>
        </p>
</div>


{% endblock content %}

    

    

templates/map.html
{% extends 'base.html' %}
{% load static %}

{% block map %}

<script src="{% static 'js/final_stones.js' %}"></script>
<script src="{% static 'js/final_index.js' %}"></script>

<link rel='stylesheet' href="{% static 'css/map_style.css' %}">

{% endblock map%}

{% block content %}
<div class="row">
    <a href="{% url 'core:home' %}" style="z-index:100;" class=" ml-5 home-button"><span class="fa fa-home"> Home</span></a>
    <!-- <div class="title">Stones Locator</div> -->

    <div class="search-container">
        <div class="search">
            <input id="stone-number-input" type="text" placeholder="Enter stone number"/>
            <i class="fa fa-search" onclick="searchStores()"></i>
        </div>
    </div>
    <div class="stores-list-container">
        <div class="stores-list">
            <div class="store-container">
                <div class="store-info-container">
                    <div class="store-address">
                        <span>March Stone No.1</span>
                        <span></span>
                    </div>
                    <div class="store-phone-number">57.152685,-2.584896</div>
                </div>
                <div class="store-number-container">
                    <div class="store-number">
                        1
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id='map'></div>

{% endblock content %}

{% block map_script %}
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key={{api_key}}&callback=initMap">
</script>
{% endblock map_script %}

templates/portfolio.html
{% extends 'base.html' %}

{% block content %}

    
    <div class="site-wrap">

      <a href="#" class="offcanvas-toggle js-offcanvas-toggle">Menu</a>
      <div class="offcanvas_menu" id="offcanvas_menu">
        <ul class="mb-5">
          <li><a href="{% url 'core:home' %}">Bio</a></li>
          <li class="active"><a href="{% url 'core:portfolio' %}">Portfolio</a></li>
          <li><a href="{% url 'core:resume' %}">Resume</a></li>
          <li><a href="{% url 'core:contact' %}">Contact</a></li>
        </ul>
        <ul class="social">
          <li><a target="_blank" href="https://www.facebook.com/mateusz.wrobel.796" class="mr-2 mb-2"><i class="fa fa-facebook"></i></a> </li>
          <li><a target="_blank" href="https://github.com/mateuszwwwrobel" class="mr-2 mb-2"><i class="fa fa-github"></i></a> </li>
          <li><a target="_blank" href="https://www.youtube.com/channel/UCqbh_cQEJo81E6RvjHllU5w/videos" class="mr-2 mb-2"><i class="fa fa-youtube"></i></a></li>
        </ul>

        </br><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

      </div>
      
      <aside style="background-image: url(/static/img/profile.png);"></aside>
      <main>
        <a href="{% url 'core:home' %}" class="home-button"><span class="fa fa-home"></span></a>
        
        
      </main>
    </div>

{% endblock content %}

templates/resume.html
{% extends 'base.html' %}

{% block content %}

    
    <div class="site-wrap">

      <a href="#" class="offcanvas-toggle js-offcanvas-toggle">Menu</a>
      <div class="offcanvas_menu" id="offcanvas_menu">
        <ul class="mb-5">
          <li><a href="{% url 'core:home' %}">Bio</a></li>
          <li><a href="{% url 'core:portfolio' %}">Portfolio</a></li>
          <li class="active"><a href="{% url 'core:resume' %}">Resume</a></li>
          <li><a href="{% url 'core:contact' %}">Contact</a></li>
        </ul>
        <ul class="social">
          <li><a target="_blank" href="https://www.facebook.com/mateusz.wrobel.796" class="mr-2 mb-2"><i class="fa fa-facebook"></i></a> </li>
          <li><a target="_blank" href="https://github.com/mateuszwwwrobel" class="mr-2 mb-2"><i class="fa fa-github"></i></a> </li>
          <li><a target="_blank" href="https://www.youtube.com/channel/UCqbh_cQEJo81E6RvjHllU5w/videos" class="mr-2 mb-2"><i class="fa fa-youtube"></i></a></li>
        </ul>

          </br><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

      </div>
      
      <aside style="background-image: url(/static/img/profile.png); transform: rotate(360deg);"></aside>
      <main>
        <a href="{% url 'core:home' %}" class="home-button"><span class="fa fa-home"></span></a>
        
      </main>
    </div>

{% endblock content %}

templates/script.html
{% load static %}

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>